redis:
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000
  data-prefix: "itssync-data:"
  state-prefix: "itssync-state:"
  message-channel: "itssync-message"

database:
  enabled: true
  host: localhost
  port: 3306
  user: root
  password: root
  database: minecraft
  table: "itssync_data"