options:
  debug: true
  crash-timeout: 50s
  max-wait-time: 10s

save:
  join: false
  quit: true
  death: true
  changeWorld: true
  worldSave: true

sync:
  advancement: true
  statistics: true
  inventory: true
  enderChest: true
  effect: false
  attribute: false
  recipeBook: false
  gamemode: false
  health: true
  maxHealth: false
  food: true
  exp: true
  fly: false
  walkSpeed: false
  air: false
  location: false
  rotation: true